package transport

import (
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strings"
)

type Producer interface {
	Start() error
}

type HTTPProducer struct {
	listenAddr     string
	produceChannel chan<- Message
}

func NewHTTPProducer(listenAddr string, produceChannel chan<- Message) *HTTPProducer {
	return &HTTPProducer{
		listenAddr:     listenAddr,
		produceChannel: produceChannel,
	}
}

// Implementing Handler interface.
// Refer to [net/http.Handler] interface.
func (p *HTTPProducer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/")
	parts := strings.Split(path, "/")

	switch r.Method {
	case http.MethodGet:
	case http.MethodPost:
		if len(parts) != 2 {
			errMsg := fmt.Sprintf(
				"invalid route param count : passed %d",
				len(parts),
			)

			slog.Error(errMsg)
			writeResponse(
				w,
				http.StatusBadRequest,
				NewErrorResponse(errMsg),
			)

			return
		}

		protoName, topicName := parts[0], parts[1]
		switch protoName {
		case "publish":
			data, err := io.ReadAll(r.Body)

			if err != nil {
				errMsg := "could not read request body for data to be published"

				slog.Error(errMsg)
				writeResponse(
					w,
					http.StatusBadRequest,
					NewErrorResponse(errMsg),
				)

				return
			}

			slog.Info("publishing under", "topic", topicName)

			p.produceChannel <- Message{
				Topic: topicName,
				Data:  data,
			}

			writeResponse(
				w,
				http.StatusCreated,

				// TODO: somehow get the offset back and return it
				// there needs to be consideration that if the producer
				// needs to know the access at all, as the consumer will
				// consume messages as and when generated by producer, not
				// by sending the offset of the message generated.
				NewPublishedResponse("message published, this offset is a mock offset", -1),
			)

		default:
			errMsg := fmt.Sprintf("route %s not supported", protoName)

			writeResponse(
				w,
				http.StatusBadRequest,
				NewErrorResponse(errMsg),
			)

			return
		}
	case http.MethodDelete:

	default:
		w.WriteHeader(405)
	}
}

func (p *HTTPProducer) Start() error {
	slog.Info("http producer started", "port", p.listenAddr)

	// http.ListenAndServe is a blocking method unless there is an error
	return http.ListenAndServe(p.listenAddr, p)
}
